# Generated by Django 6.0.5 on 2026-09-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatMed',
            fields=[
                ('cd_mat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_mat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Insumo')),
                ('ds_marca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('ds_tipo', models.CharField(blank=True, choices=[('Material Hospitalar', 'Material Hospitalar'), ('Medicamento', 'Medicamento')], max_length=50, null=True, verbose_name='Categoria')),
                ('unidade_med', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade de Medida')),
                ('cd_tiss', models.CharField(blank=True, choices=[('19', 'Brasíndice'), ('20', 'TUSS')], max_length=2, null=True, verbose_name='Tabela TISS')),
                ('cd_tuss', models.CharField(max_length=8, verbose_name='Código TUSS')),
                ('cd_simpro', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SIMPRO')),
                ('cd_brasindice', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Brasíndice')),
                ('ds_pessoaj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materiais', to='pessoa_juridica.pessoajuridica')),
            ],
        ),
    ]
