# Generated by Django 6.0.5 on 2026-09-26 21:53

from django.db import migrations


def clear_and_reset(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        try:
            cursor.execute('TRUNCATE TABLE anuncio_anuncio RESTART IDENTITY CASCADE;')
            cursor.execute('TRUNCATE TABLE mat_med_matmed RESTART IDENTITY CASCADE;')
        except Exception:
            pass

        tabelas_antigas = ['lote_lote', 'fabricante_fabricante', 'marcas_marcas', 'tipo_matmed_tipomatmed']
        for tabela in tabelas_antigas:
            try:
                cursor.execute(f'DROP TABLE IF EXISTS {tabela} CASCADE;')
            except Exception:
                pass

    # Criptografar senhas de usuários existentes que estão em texto puro
    PessoaJuridica = apps.get_model('pessoa_juridica', 'PessoaJuridica')
    from django.contrib.auth.hashers import make_password
    
    for pessoa in PessoaJuridica.objects.all():
        # Senhas do Django com PBKDF2 sempre começam com pbkdf2_
        if pessoa.senha_pj and not pessoa.senha_pj.startswith('pbkdf2_'):
            pessoa.senha_pj = make_password(pessoa.senha_pj)
            pessoa.save(update_fields=['senha_pj'])

class Migration(migrations.Migration):

    dependencies = [
        ('mat_med', '0001_initial'),
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_and_reset),
    ]
