# Generated by Django 6.0.5 on 2026-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0002_pessoajuridica_bairro_pessoajuridica_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='interesses_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
