# Generated by Django 6.0.5 on 2026-10-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0003_pessoajuridica_interesses_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='saldo_creditos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
