# Generated by Django 6.0.5 on 2026-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0003_pessoajuridica_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
