# Generated by Django 6.0.5 on 2026-09-20 21:41

from django.db import migrations

def create_admin_user(apps, schema_editor):
    PessoaJuridica = apps.get_model('pessoa_juridica', 'PessoaJuridica')
    # Use the valid CNPJ we generated earlier
    cnpj = '06526328000122'
    if not PessoaJuridica.objects.filter(nr_cnpj=cnpj).exists():
        PessoaJuridica.objects.create(
            nm_pessoaj='Administrador do Sistema',
            email_pj='admin@medconnect.com.br',
            senha_pj='Admin123!',
            resp_tec='Admin Master',
            nr_cnpj=cnpj,
            razao_social='MedConnect Admin',
            status='ATIVA',
            is_admin=True
        )
    else:
        # Se já existir, força ser admin
        user = PessoaJuridica.objects.get(nr_cnpj=cnpj)
        user.is_admin = True
        user.status = 'ATIVA'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0004_pessoajuridica_is_admin'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
