# Generated by Django 6.0.5 on 2026-10-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa_juridica', '0004_pessoajuridica_saldo_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('quantidade_creditos', models.PositiveIntegerField()),
                ('bonus_creditos', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destaque', models.BooleanField(default=False, help_text='Exibe o selo "Mais popular".')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pacote de Créditos',
                'verbose_name_plural': 'Pacotes de Créditos',
                'ordering': ('ordem', 'preco'),
            },
        ),
        migrations.CreateModel(
            name='TransacaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('D', 'Consumo'), ('E', 'Estorno'), ('B', 'Bônus / Ajuste')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Recusada')], default='A', max_length=1)),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo_apos', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('funcionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], max_length=10, null=True)),
                ('codigo_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='creditos.pacotecredito')),
                ('pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacoes_credito', to='pessoa_juridica.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Transação de Crédito',
                'verbose_name_plural': 'Transações de Crédito',
                'ordering': ('-data_transacao', '-id'),
                'indexes': [models.Index(fields=['pessoa_juridica', '-data_transacao'], name='creditos_tr_pessoa__0ba795_idx')],
            },
        ),
    ]
