# Generated by Django 6.0.5 on 2026-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0002_pessoajuridica_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='imagem_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
