# Generated by Django 6.0.5 on 2026-09-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mat_med', '0001_initial'),
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('nr_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('ds_lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('dt_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('dt_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('qtd_mat', models.IntegerField()),
                ('val_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ds_obs', models.CharField(blank=True, default='', max_length=2000)),
                ('data_anuncio', models.DateField(auto_now_add=True)),
                ('ie_status', models.CharField(choices=[('A', 'Ativo'), ('N', 'Em Negociação'), ('F', 'Finalizado'), ('I', 'Inativo')], default='A', max_length=1)),
                ('imagem_anuncio', models.TextField(blank=True, null=True, verbose_name='Imagem do Anúncio (Base64)')),
                ('val_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('val_aceito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cd_mat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='mat_med.matmed')),
                ('cd_pessoa_anunciante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='pessoa_juridica.pessoajuridica')),
                ('cd_pessoa_compradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios_comprados', to='pessoa_juridica.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
