# Generated by Django 6.0.5 on 2026-09-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
        ('pessoa_juridica', '0002_pessoajuridica_bairro_pessoajuridica_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val_proposta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_proposta', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Recusada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('ds_obs', models.TextField(blank=True, default='')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacoes', to='anuncio.anuncio')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='negociacoes_enviadas', to='pessoa_juridica.pessoajuridica')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='negociacoes_recebidas', to='pessoa_juridica.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Negociação',
                'verbose_name_plural': 'Negociações',
            },
        ),
    ]
