# Generated by Django 6.0.5 on 2026-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_negociacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='ie_status',
            field=models.CharField(choices=[('A', 'Ativo'), ('N', 'Em Negociação'), ('F', 'Finalizado'), ('I', 'Inativo / Rascunho'), ('S', 'Saldo de Venda Parcial')], default='A', max_length=1),
        ),
    ]
