# Generated by Django 6.0.5 on 2026-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0008_anuncio_val_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem_anuncio',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem do Anúncio (Base64)'),
        ),
    ]
